language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4

script:
 - pip install -r requirements-dev.txt
 - make mongo-start
 - make mongo-config
 - python setup.py build
 - make test

